### ISSUE TITLE
__init__() got an unexpected keyword argument 'r'

### ISSUE THREAD

**Issue by W-ZChi** [heekhero/DTL#1]
File "/raid5/usr/peft/DTL-main/train_vit_vtab.py", line 173, in main
    model = create_model(args.model, num_classes=args.num_classes, checkpoint_path=args.load_path, drop_path_rate=args.drop_path, r=args.r, fusion_size=args.fusion_size, lora_before_blocks=args.lora_before_blocks, add_after_blocks=args.add_after_blocks, beta=args.beta, log_file=args.log_file)
  File "/raid5/usr/peft/DTL-main/train_vit_vtab.py", line 367, in <module>
    main()
TypeError: __init__() got an unexpected keyword argument 'r'

**Comment by heekhero** [comment]
Hi, could you please provide a more detailed training log? This error may have occurred due to an incorrect model selection. Please ensure that your model is "vit_base_patch16_224_in21k" and strictly set your timm version to 0.5.4.

**Comment by zhangs669** [comment]
看上去好像是创建模型的函数用错了？create_model来自timm，但是从r开始后面一大堆的自定义参数。

**Comment by heekhero** [comment]
实现的时候对timm的Model函数进行了改写，所以后面的自定义参数都是合法的，都是DTL需要用到的参数。还有一点就是请确保timm的版本是0.5.4
