### ISSUE TITLE
About the Best Performance Described in the Paper

### ISSUE THREAD

**Issue by Lucenova** [heekhero/DTL#2]
About the Best Performance Described in the Paper, we would like to express our appreciation to the authors for their outstanding work. Could you please provide the parameter settings of the best-performing model? thx

**Comment by heekhero** [comment]
Thank you for your interest in our work. The best hyper-parameters for various experiments can be found in the 'train_scripts' directory at [https://github.com/heekhero/DTL/tree/main/train_scripts]. This directory includes all the training scripts for our main experiments as listed in Tables 2, 3, and 4, and Figure 3.

**Comment by Lucenova** [comment]
> Thank you for your interest in our work. The best hyper-parameters for various experiments can be found in the 'train_scripts' directory at [https://github.com/heekhero/DTL/tree/main/train_scripts]. This directory includes all the training scripts for our main experiments as listed in Tables 2, 3, and 4, and Figure 3.

In the 'train_scripts' directory at [https://github.com/heekhero/DTL/tree/main/train_scripts], there is no DTL+* setting, as the paper show, DTL+* is set M = 1, but when I change the add_after_blocks from 6-11 to 0-11 in  DTL+ bash, the other parameter is keep still, I find the result is 0.772. So I think may be the DTL+* may have there own settings, could you provide the settings? THX
